# Generated by Django 4.2.2 on 2023-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homie', '0002_rename_name_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
